version: '3.9'

services:
  import-data:
    build: .
    volumes:
      - ${PATH_TO_SYNTHEA_CSV}:/data/input/synthea-csv:ro
      - ${PATH_TO_OMOP_CDM_VOCAB_FILES}:/data/input/omop-cdm:ro
      - ./.env:/app/.Renviron:ro
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
  postgres:
    image: postgres:14.2
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ${PATH_TO_POSTGRES_STORAGE_LOCATION}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  pgadmin:
    image: dpage/pgadmin4:6.6
    ports:
      - "80:80"
    volumes:
      - ${PATH_TO_PGADMIN_DATA}:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

networks:
  omopdb:
